// Portuguese mirror of ../../cases/sophia-mental-health.ts. Text only: images come from the English file. Wording follows João's own Portuguese article.
import * as en from '../../cases/sophia-mental-health';
import { translateBody } from './blocks';

export const meta: Record<keyof typeof en.meta, string> = { ...en.meta, company: 'Projeto de estudo · curso UX Unicórnio' };

export const original = { title: 'Fortalecendo a saúde mental dos brasileiros através da Sophia', subtitle: 'Como utilizamos UX Design para entender as barreiras que impedem a procura de tratamentos para saúde mental e para fomentar essa prática em todo território nacional.' };

export const body = translateBody(en.body, [
  { type: 'img', alt: 'Vista isométrica das telas do app Sophia (onboarding, match, lista de psicólogos, videochamada) ao lado do logo roxo e laranja da Sophia' },
  { type: 'h2', text: 'O desafio' },
  { type: 'p', text: 'Saúde mental ainda é um tema negligenciado por grande parte da população, em um país em que [1 a cada 2 brasileiros já pensaram em tirar a própria vida](https://catracalivre.com.br/saude-bem-estar/um-em-cada-dois-brasileiros-ja-pensou-em-se-suicidar-revela-pesquisa/). Em meio a um cenário que já era caótico e **se intensifica dia após dia com uma pandemia a nível global**, nosso time, composto por:' },
  { type: 'ul', items: [
      '[João Vitor Fatoretto](https://www.linkedin.com/in/joaovitorfatoretto/?locale=en_US)',
      '[Paulo Ortega](https://www.linkedin.com/in/phortega/)',
      '[Rodrigo Vicenzo](https://br.linkedin.com/in/rodrigovicenzo)',
    ] },
  { type: 'p', text: 'decidiu aceitar o seguinte desafio:' },
  { type: 'p', text: '“Fortalecer a saúde mental dos brasileiros utilizando UX Design”' },
  { type: 'h2', text: 'Entendendo o problema' },
  { type: 'p', text: '[De acordo com a OMS, o Brasil é o país mais ansioso do mundo](https://www.em.com.br/app/noticia/saude-e-bem-viver/2022/07/03/interna_bem_viver,1376936/brasil-o-pais-mais-ansioso-do-mundo.shtml) e, para piorar, houve um [aumento de 80% desses casos só durante a pandemia e outro aumento de 50% nos casos de depressão](https://veja.abril.com.br/saude/casos-de-depressao-e-de-ansiedade-dobram-durante-quarentena/). Isto é, um total de quase **20 milhões de brasileiros com transtorno de ansiedade** e mais de **12 milhões com depressão.** Além disso, em média, [**24% dos casos de ansiedade evoluirão para depressão**](https://www.estarsaudemental.com.br/depressao-ansiosa/#:~:text=Estima-se%20que%20em%2024,evoluir%20para%20um%20quadro%20ansioso%E2%80%9D.&text=Preste%20aten%C3%A7%C3%A3o%20nestes%20dados:%20estima,Transtorno%20Depressivo%20Maior%20%28TDM%29), o que torna o quadro ainda mais grave.' },
  { type: 'p', text: 'O cenário é preocupante, sem previsão de melhora. Nesse caos, os psicólogos se apresentam como os principais agentes para o tratamento desses casos, entretanto, **ainda existem barreiras que impedem a melhora da situação.**' },
  { type: 'h2', text: 'Objetivo do projeto' },
  { type: 'p', text: '“Nosso objetivo é **entender as barreiras que dificultam que o brasileiro cuide da sua saúde mental e realize os tratamentos necessários** e, assim, criar uma solução para contorná-las.”' },
  { type: 'p', text: 'Antes de ganhar escala, o foco será garantir a melhor solução para o problema dos usuários com o menor esforço. Portanto, trabalharemos com um número reduzido de usuários, usando duas metas principais (baseadas no framework H.E.A.R.T.):' },
  { type: 'ul', items: [
      'Satisfação: atingir NPS maior que 75 (zona de excelência) nos 6 primeiros meses;',
      'Retenção: ter pelo menos 60% dos usuários ativos (usuários que fazem sessões recorrentes) nos 6 primeiros meses.',
    ] },
  { type: 'p', text: 'Após o estágio de validação inicial, direcionaremos nossas metas para escalar a solução, ou seja, focaremos principalmente no número de usuários.' },
  { type: 'h2', text: 'Criando empatia' },
  { type: 'p', text: 'Para entender mais a fundo quem e como são essas pessoas, construímos três protopersonas, baseadas na nossa pesquisa de mesa. Elas nos serviram como guia para conduzir nossas pesquisas e foram estruturadas na forma de uma matriz CSD para cada uma, o que nos ajudou a validar nossas suposições e entender quais realmente eram as dores dos usuários. Nossas principais suposições e dúvidas iniciais foram:' },
  { type: 'img', alt: 'Principais suposições e dúvidas da nossa matriz CSD', caption: 'Principais suposições e dúvidas da nossa matriz CSD' },
  { type: 'h3', text: 'Pesquisa quantitativa' },
  { type: 'p', text: 'Criamos dois formulários, um para pacientes e um para psicólogos, baseando as perguntas nas hipóteses e dúvidas mais relevantes da nossa matriz CSD. O questionário voltado aos pacientes, com quase 250 respostas, nos ajudou a entender mais sobre os usuários.' },
  { type: 'p', text: 'Confira o [dashboard interativo feito no Google Data Studio](https://datastudio.google.com/reporting/21a883f1-cc10-4731-a5ea-862f6cdb2c0f).' },
  { type: 'p', text: '**Pacientes**' },
  { type: 'img', alt: 'Dos homens: 61% buscam ajuda profissional quando precisam; 77% falam sobre seus problemas e sentimentos, mesmo que só quando não estão bem; só 4% dos que afirmaram não precisar de um psicólogo disseram já ter pensado ou tentado tirar a própria vida.', caption: 'Dados que invalidam algumas das nossas hipóteses iniciais' },
  { type: 'p', text: 'O homem contemporâneo dá mais importância do que pensávamos à sua saúde mental. Apesar disso, entre os homens que afirmaram não ir ao psicólogo porque não precisam (o estereótipo de homem das nossas protopersonas), apenas 4% disseram já ter pensado ou tentado tirar a própria vida. Esse valor contrasta muito com a totalidade da pesquisa, na qual mais de 55% afirmaram já ter pensado em suicídio. Nossa conclusão é que **eles não querem e acreditam que não precisam da ajuda desses profissionais** e, consequentemente, da nossa.' },
  { type: 'img', alt: '55% dos respondentes já pensaram em tirar a própria vida.', caption: 'Dados relevantes de todos os participantes' },
  { type: 'p', text: 'Por outro lado, a pesquisa não só nos ajudou a **ter certeza de que algumas suposições eram válidas**, como também **nos trouxe novos insights** de como poderíamos resolver o desafio:' },
  { type: 'img', alt: '20% fazem terapia com regularidade. 58% não cuidam da saúde mental de nenhuma forma. 30% pararam de ir ou nunca foram ao psicólogo por motivos financeiros. 13% das mulheres e 10% de todos os participantes não se sentem confortáveis em ir ao psicólogo.', caption: 'Dados que trouxeram novas oportunidades para explorarmos' },
  { type: 'p', text: 'Esses dados, especialmente os dois últimos, nos trouxeram várias indagações para investigarmos mais a fundo, já que sabemos que…' },
  { type: 'p', text: '“… há discrepância entre o que as pessoas falam e o que elas realmente pensam, sentem e como agem.”' },
  { type: 'p', text: '**Psicólogos**' },
  { type: 'p', text: 'A pesquisa quantitativa com os psicólogos, apesar de não ser tão reveladora quanto a parte qualitativa, nos deu alguns direcionamentos do que poderíamos explorar:' },
  { type: 'img', alt: '96% já atendem online por causa da pandemia. 40% apontaram a falta de privacidade como um problema.', caption: 'Dados importantes sobre a pesquisa com psicólogos' },
  { type: 'ul', items: [
      '_Será que o “online” ainda é um problema?_',
      '_Como e por que esses problemas relacionados aos espaços virtuais acontecem?_',
      '_Como esses profissionais conseguem novos clientes?_',
    ] },
  { type: 'h3', text: 'Pesquisa qualitativa' },
  { type: 'p', text: 'Fizemos **entrevistas de empatia para aprofundar nos porquês e nos sentimentos** dos nossos usuários, todos relacionados a pontos levantados nas pesquisas quantitativas.' },
  { type: 'p', text: 'Para elaborar os **roteiros das entrevistas**, atrelamos cada um dos pontos que gostaríamos de entender melhor a uma pergunta aberta com observações do que deveria ser aprofundado, como e por quê.' },
  { type: 'img', alt: 'Trecho retirado do roteiro de entrevistas do paciente', caption: 'Trecho retirado do roteiro de entrevistas do paciente' },
  { type: 'p', text: 'Acesse o [roteiro de pesquisa completo](https://docs.google.com/document/d/1PqHnOEeD0RZYaiGSYMs77eUcSsUeFr7MmYmCZOy-aCY/edit?usp=sharing).' },
  { type: 'p', text: 'Após realizarmos mais de 20 entrevistas, pudemos observar padrões que nos elucidaram pontos-chave para a continuação do projeto:' },
  { type: 'p', text: '**Pacientes**' },
  { type: 'ol', items: [
      '**O “problema financeiro” não era tão “financeiro” assim.** Existem várias iniciativas populares e alternativas baratas para quem não pode pagar. O que acontece é que, na maioria das vezes, **as pessoas não encontram um psicólogo de quem gostem, com quem se sintam à vontade e em quem confiem de verdade** nesses lugares. _Aqueles “10%” da pesquisa quantitativa se mostraram bem mais expressivos do que pareciam._',
      '**As pessoas querem resultados rápidos.** Quando finalmente encontram um bom profissional, **a maioria para o tratamento após sentir uma leve melhora.** Consequentemente, os sintomas voltam, gerando um ciclo vicioso.',
      '**Terapia online é uma alternativa.** Muitas pessoas que começaram a fazer terapia online se sentiram mais confortáveis por estarem em um ambiente pessoal atrás de suas telas, assim, **se sentem mais seguras para falar de seus problemas.**',
    ] },
  { type: 'p', text: '**Psicólogos**' },
  { type: 'ol', items: [
      '**Ainda preferem muito mais o atendimento presencial ao online.** Os psicólogos, na verdade, têm bastante facilidade com atendimentos virtuais e veem muitas vantagens nisso, mas ainda pensam que **é importante ter um ambiente presencial.**',
      '**A captação de clientes é um problema.** Os psicólogos conquistam clientes pelo boca a boca e pelo convênio. O primeiro é um processo lento e o segundo não dá um bom lucro.',
    ] },
  { type: 'h3', text: 'Personas e mapa de jornada do usuário' },
  { type: 'p', text: 'Para assimilarmos e alinharmos essas novas descobertas como time, redesenhamos as 3 personas e suas respectivas jornadas:' },
  { type: 'img', alt: 'Persona 1', caption: 'Persona 1' },
  { type: 'img', alt: 'Mapa de jornada do usuário para a persona 1', caption: 'Mapa de jornada do usuário para a persona 1' },
  { type: 'p', text: 'Veja as [3 personas e o mapa de jornada do usuário completos](https://docs.google.com/presentation/d/1JhYKJ4DjQBzZbRSdxegeLJnJQzrMQmmBaH0QdSv7iyk/edit?usp=sharing).' },
  { type: 'h2', text: 'Ideação' },
  { type: 'p', text: 'Com as personas e jornadas validadas em mãos, utilizamos o “Como poderíamos?” para **fazer a ponte entre os nossos aprendizados e a geração de ideias.** Reescrevemos cada um dos pontos principais utilizando o framework em post-its virtuais e **os priorizamos em uma matriz de impacto vs esforço** utilizando o Miro.' },
  { type: 'img', alt: 'Matriz de impacto vs esforço', caption: 'Matriz de impacto vs esforço' },
  { type: 'p', text: 'Identificamos pela matriz o que era mais relevante para o usuário e para o negócio e o que precisaria de menos esforço.' },
  { type: 'p', text: 'Selecionamos os principais “como poderíamos” e usamos para gerar as ideias de solução, separando **um único foco principal** e pontos importantes para complementá-lo, seguidos de pontos secundários, mas ainda **relevantes para a experiência como um todo.**' },
  { type: 'img', alt: '“Como poderíamos” priorizado', caption: '“Como poderíamos” priorizado' },
  { type: 'p', text: 'Para cada um desses pontos, geramos várias ideias de solução — primeiro individualmente e depois em grupo — , utilizando 4 constraints: _soluções que poderíamos construir com 1 bilhão de dólares, sem dinheiro nenhum, usando mágica e com tecnologias futuristas._ Apesar de algumas ideias geradas com esse framework parecerem impossíveis de implementar, **ao longo do processo fica fácil tangibilizá-las e é aí que surgem várias soluções inovadoras.**' },
  { type: 'p', text: 'De todas essas ideias, votamos nas melhores e discutimos sobre cada uma delas, levando em conta pontos como **viabilidade técnica, recursos disponíveis, relevância para o negócio e como essas ideias poderiam interagir entre si.** Assim, começamos a **aprofundar a solução.**' },
  { type: 'img', alt: 'Proposta de valor da solução', caption: 'Proposta de valor da solução' },
  { type: 'img', alt: 'Definindo a solução', caption: 'Definindo a solução' },
  { type: 'p', text: 'Acesse o [processo de ideação completo no Miro](https://miro.com/app/board/uXjVPdM9iY0=/?share_link_id=83332698073).' },
  { type: 'h2', text: 'Benchmarking' },
  { type: 'p', text: 'Decidimos analisar nossos concorrentes apenas após termos uma ideia mais concreta da solução, para não induzi-la, mantendo a inovação, mas ainda tentando aumentar nossa vantagem competitiva. Com isso, mapeamos 5 concorrentes — [Vittude](https://www.vittude.com/), [Zenklub](https://zenklub.com.br/), [CVV](https://www.cvv.org.br/), [7 cups](https://www.7cups.com/) e [Fepo](https://www.fepo.com.br/) — , analisamos cada um deles e criamos uma tabela comparativa entre eles.' },
  { type: 'img', alt: 'Tabela comparativa entre os concorrentes', caption: 'Tabela comparativa entre os concorrentes' },
  { type: 'p', text: 'Após a análise, chegamos às seguintes conclusões:' },
  { type: 'ul', items: [
      'Atendimento emergencial e programa de ouvintes voluntários podem ser um diferencial competitivo, já que não existem em plataformas de psicologia brasileiras (o 7cups é estrangeiro e o CVV não é uma plataforma completa, apenas um número de telefone para situações de emergência);',
      'Ainda há espaço para desenvolver uma triagem inicial que entenda melhor o paciente de acordo com seu relato, não com autodiagnóstico (o que a maioria faz) — nossa solução começa a fazer isso com a triagem de sentimentos e a inteligência artificial de match, cujo algoritmo aprende conforme faz mais matches;',
      'Podemos trabalhar com planos B2B para atingir esse mercado;',
      'Aproveitamos a ideia do 7cups para criar trilhas de crescimento pessoal focadas em complementar o tratamento psicológico com etapas individuais.',
    ] },
  { type: 'h2', text: 'Protótipo da solução' },
  { type: 'img', alt: 'Um dos desenhos da plataforma usando o framework Crazy Eights', caption: 'Um dos desenhos da plataforma usando o framework Crazy Eights' },
  { type: 'p', text: 'Antes de começar a fazer os desenhos no papel como na foto acima, discutimos qual tecnologia usaríamos para a solução, dado que, ao dizer “fortalecer a saúde mental dos brasileiros”, queremos dizer todos eles — portanto, **precisamos ser inclusivos.** Aplicativos mobile têm, na nossa opinião, uma experiência mais imersiva, entretanto, **eles exigem um espaço livre de memória que smartphones simples e antigos não têm.**' },
  { type: 'p', text: 'Então optamos pelo melhor dos dois mundos: o **PWA (Progressive Web App)**, que traz **a experiência imersiva, sem a necessidade de fazer download** e também é **acessível pelo computador**. Ele também vai nos ajudar no desenvolvimento da solução, **necessitando de menos esforço**, porque precisaríamos de menos desenvolvedores para as diferentes plataformas e também de um código mais simples, baseado em HTML, CSS e Javascript com acesso a funções nativas.' },
  { type: 'h3', text: 'Crazy Eights' },
  { type: 'p', text: 'Dito isso, utilizando o conceito de mobile first, desenhamos as telas do aplicativo usando os Crazy Eights. Foi um momento em que surgiram várias formas de desenhar as mesmas soluções, sempre tendo as personas e suas jornadas em mente.' },
  { type: 'img', alt: 'Esboços em papel, feitos à mão, de seis telas do app: splash com o logo, escolha entre paciente ou profissional, uma introdução ao app, um questionário, uma lista de profissionais com match e o perfil de um profissional com vídeo' },
  { type: 'img', alt: 'Oito esboços em papel de telas do app do exercício Crazy Eights: home pós-match, tutorial, escolha de uma trilha e as etapas do questionário de match' },
  { type: 'img', alt: 'Mais oito esboços em papel: home com o botão de match, o match em andamento, o perfil do profissional com match, a tela de SOS, conteúdos, conquistas, terapia com chat e a agenda do psicólogo' },
  { type: 'img', alt: 'Diferentes esboços das telas do app usando Crazy Eights', caption: 'Diferentes esboços das telas do app usando Crazy Eights' },
  { type: 'h3', text: 'Fluxo das telas' },
  { type: 'p', text: 'Para consolidar nossas ideias antes de seguirmos para os wireframes, montamos o fluxo de telas do aplicativo.' },
  { type: 'img', alt: 'Fluxo das telas', caption: 'Fluxo das telas' },
  { type: 'h3', text: 'Protótipo de baixa fidelidade' },
  { type: 'p', text: 'Revisitamos as personas e a jornada, nossos esboços e o fluxo de telas para destacar os pontos importantes e amarrar tudo em uma experiência que gera valor para o usuário, resolvendo o problema dele com boa usabilidade.' },
  { type: 'p', text: 'Ou seja, desenhamos os wireframes no Figma, definindo a arquitetura da informação e o posicionamento dos elementos em um protótipo de baixa fidelidade:' },
  { type: 'img', alt: 'Telas do app em um protótipo de baixa fidelidade', caption: 'Telas do app em um protótipo de baixa fidelidade' },
  { type: 'p', text: 'Navegue nos [wireframes completos](https://www.figma.com/proto/StBNiTWGf0ysP4whg9TLZ9/Grupo_UX_Unic%C3%B3rnio?node-id=402%3A2&scaling=scale-down).' },
  { type: 'h2', text: 'Testes de usabilidade' },
  { type: 'p', text: 'O protótipo de baixa fidelidade foi testado com 5 usuários nas seguintes tarefas:' },
  { type: 'ul', items: [
      '_Buscar um psicólogo_',
      '_Iniciar uma sessão de terapia virtual_',
      '_Acionar um atendimento emergencial_',
    ] },
  { type: 'h3', text: 'Relatório dos testes' },
  { type: 'p', text: '_Alerta: spoilers do protótipo de alta fidelidade!_' },
  { type: 'p', text: '**1. Fazer o match antes de se cadastrar.** O motivo é ter uma barreira a menos para o usuário perceber o valor que a plataforma entrega e diminuir a taxa de desistência. Com isso, a próxima etapa depois do onboarding passou a ser o match, não o cadastro.' },
  { type: 'img', alt: 'Comparação da última tela do onboarding antes e depois dos testes', caption: 'Comparação da última tela do onboarding antes e depois dos testes' },
  { type: 'p', text: '**2. Botão de match não encontrado.** 100% dos usuários não identificaram a lupa e o card dela como um botão de ação, então tivemos que redesenhá-lo.' },
  { type: 'img', alt: 'Comparação da tela de match antes e depois dos testes', caption: 'Comparação da tela de match antes e depois dos testes' },
  { type: 'p', text: '**3. Dificuldades em responder o questionário.** Isso aconteceu principalmente porque sentimentos, emoções e sintomas físicos geralmente vêm em diferentes intensidades, então colocamos eles em uma escala numérica.' },
  { type: 'img', alt: 'Comparação de uma das telas do questionário antes e depois dos testes', caption: 'Comparação de uma das telas do questionário antes e depois dos testes' },
  { type: 'p', text: '**4. Atendimento virtual não encontrado.** Os usuários tiveram dificuldade em encontrar o acesso ao atendimento virtual, então criamos um botão de acesso no card da terapia agendada e também um menu de atendimentos.' },
  { type: 'img', alt: 'Comparação da tela inicial antes e depois dos testes', caption: 'Comparação da tela inicial antes e depois dos testes' },
  { type: 'h3', text: 'Teste de escrita' },
  { type: 'p', text: 'Nos testes de usabilidade, também percebemos que os usuários passavam rápido pelas telas explicativas do onboarding sem ler. Então, **usando a ferramenta** [**_VisualEyes_**](https://www.visualeyes.design/)**, analisamos a legibilidade e a atenção do usuário** nessas telas. Como resultado, **reescrevemos e diminuímos os textos** e **adicionamos um botão “pular”**, criando uma experiência mais fácil de ler e de entender, e também menos cansativa para os usuários apressados.' },
  { type: 'img', alt: 'Comparação de uma das telas de onboarding antes e depois dos testes', caption: 'Comparação de uma das telas de onboarding antes e depois dos testes' },
  { type: 'h2', text: 'Branding' },
  { type: 'h3', text: 'Naming' },
  { type: 'p', text: 'O processo de naming foi baseado em dois aspectos:' },
  { type: 'ol', items: [
      '**Saúde mental** (segmento)',
      '**Afinidade** entre o psicólogo e o paciente (proposta de valor)',
    ] },
  { type: 'p', text: 'A partir deles, um desdobramento foi feito em um brainstorm, de onde surgiram opções mais criativas.' },
  { type: 'img', alt: 'Processo de naming a partir dos aspectos principais', caption: 'Processo de naming a partir dos aspectos principais' },
  { type: 'p', text: '**Sophia.**' },
  { type: 'p', text: 'Do grego **sophía**, significa sabedoria e transmite a ideia de autoconhecimento.' },
  { type: 'p', text: 'Acreditamos que “Sophia” transmite mais empatia, abertura e humanidade ao usuário por ser um nome personificado.' },
  { type: 'p', text: '“Sophia guiará você na busca do melhor profissional para superar seus conflitos e crises, ajudando a fortalecer sua saúde mental e proporcionar autoconhecimento, além de estar sempre presente ‘na alegria e na tristeza’.”' },
  { type: 'h3', text: 'Logo' },
  { type: 'img', alt: 'Conceito do logo: um par de alianças (aliança, conexão, parceria) mais um abraço (empatia, afinidade) forma o “S” da Sophia, dois arcos que terminam em pontos, como duas pessoas se abraçando' },
  { type: 'img', alt: 'Raciocínio de criação do logo', caption: 'Raciocínio de criação do logo' },
  { type: 'p', text: '**Cores**' },
  { type: 'p', text: '**Laranja** mistura emoções ativas e revigorantes, que procuram suscitar sentimentos de vitalidade e felicidade.' },
  { type: 'p', text: '_Associações: energia, entusiasmo, prosperidade, cordialidade, mudança._' },
  { type: 'p', text: '**Roxo** transmite tranquilidade e ajuda na criatividade, demonstrando sofisticação.' },
  { type: 'p', text: '_Associações: espiritualidade, autenticidade, veracidade, qualidade, introspecção._' },
  { type: 'h2', text: 'Guia de estilos' },
  { type: 'p', text: '**Cores:** com elas praticamente definidas, escolhemos algumas variações das cores da marca para podermos aplicá-las no protótipo, e também algumas outras complementares.' },
  { type: 'img', alt: 'Cores do guia de estilos', caption: 'Cores do guia de estilos' },
  { type: 'p', text: '**Tipografia:** optamos por duas fontes diferentes para títulos e texto, ambas sem serifa, trazendo consigo uma sensação de modernidade — principal razão pela qual escolhemos a DIN Next Rounded LT Pro, que fortalece a mensagem com formas arredondadas. Já a Source Sans Pro, para o texto, possui ótima legibilidade, além de ser uma fonte muito utilizada na web, o que agiliza o carregamento da página.' },
  { type: 'img', alt: 'Tipografia do guia de estilos', caption: 'Tipografia do guia de estilos' },
  { type: 'p', text: '**Botões e formulários:** escolhemos formas um pouco arredondadas, mas nem tanto, a meio caminho entre leveza e seriedade.' },
  { type: 'img', alt: 'Botões e formulários do guia de estilos', caption: 'Botões e formulários do guia de estilos' },
  { type: 'h2', text: 'Protótipo de alta fidelidade' },
  { type: 'p', text: 'Por fim, construímos o protótipo de alta fidelidade no Adobe XD, com base nos wireframes, nos testes de usabilidade e no guia de estilos.' },
  { type: 'p', text: 'Confira o [protótipo navegável completo](https://xd.adobe.com/view/ce110830-589e-4dc4-b04e-c3637b9199ce-9b42/screen/4e9a3691-3271-4e5a-8fd8-f47c2277b99b/).' },
  { type: 'img', alt: 'Telas do app em um protótipo de alta fidelidade', caption: 'Telas do app em um protótipo de alta fidelidade' },
  { type: 'h2', text: 'Próximos passos' },
  { type: 'p', text: 'Como consequência da priorização, levantamos alguns pontos importantes para serem desenvolvidos depois do lançamento do MVP (Mínimo Produto Viável). São eles:' },
  { type: 'ul', items: [
      'IA (Inteligência Artificial) que converse e aconselhe os pacientes',
      'Clínicas presenciais em grandes metrópoles para os psicólogos usarem e oferecerem atendimento presencial (eliminando a necessidade e a maior parte dos gastos com um local físico por parte deles)',
    ] },
  { type: 'p', text: 'Além disso, o projeto ainda tem espaço para aprimoramento, já que sabemos que o desenvolvimento de um produto nunca termina.' },
  { type: 'p', text: '“Os usuários mudam com o tempo, assim como deve acontecer com o produto.”' },
  { type: 'h2', text: 'Considerações finais' },
  { type: 'p', text: 'Agradecemos aos **nossos mentores** [**Leandro Rezende**](https://www.linkedin.com/in/lbrezende/?locale=en_US) **e** [**Rafael Frota**](https://www.linkedin.com/in/imrafaelfrota/?locale=en_US)**, do** [**UX Unicórnio**](https://www.linkedin.com/school/uxunicornio/), por todo o aprendizado que tivemos nessa caminhada.' },
  { type: 'h2', text: 'Contato dos integrantes do time' },
  { type: 'ul', items: [
      '[LinkedIn João Vitor Fatoretto](https://www.linkedin.com/in/joaovitorfatoretto/?locale=en_US)',
      '[LinkedIn Rodrigo Vicenzo](https://br.linkedin.com/in/rodrigovicenzo)',
      '[LinkedIn Paulo Ortega](https://www.linkedin.com/in/phortega/)',
    ] },
], 'sophia-mental-health');
