// Content from João's Medium article (English version), corrected in ../resume/master/case-studies/sophia-mental-health.md.
// Inline markup: **bold**, _italic_, [link](url).
import type { CaseBody } from './types';

export const meta = { company: 'Study project · UX Unicórnio course', year: '2020', role: 'UX/UI Designer', team: 'Paulo Ortega, Rodrigo Vicenzo' } as const;

export const original = { title: 'Strengthening Brazilians’ mental health through Sophia', subtitle: 'How we used UX Design to understand the barriers that prevent the search for mental health treatments and to encourage this practice throughout the national territory.' };

export const cover = { src: '/cases/sophia-mental-health/cover.jpg', w: 1920, h: 1080 };
export const card = { src: '/cases/sophia-mental-health/card.jpg', w: 1920, h: 1080 };

export const body: CaseBody = [
  { type: 'img', src: '/cases/sophia-mental-health/01.jpg', alt: 'Isometric view of the Sophia app screens (onboarding, match, psychologist list, video call) next to the purple and orange Sophia logo', w: 2000, h: 816 },
  { type: 'h2', text: 'The challenge' },
  { type: 'p', text: 'Mental health is still a neglected theme for most Brazilians, in a country where [1 in every 2 inhabitants already thought about taking their own lives](https://catracalivre.com.br/saude-bem-estar/um-em-cada-dois-brasileiros-ja-pensou-em-se-suicidar-revela-pesquisa/). In a scenario that was already chaotic and **intensifies day after day because of a global pandemic**, our team, composed of:' },
  { type: 'ul', items: [
      '[João Vitor Fatoretto](https://www.linkedin.com/in/joaovitorfatoretto/?locale=en_US)',
      '[Paulo Ortega](https://www.linkedin.com/in/phortega/)',
      '[Rodrigo Vicenzo](https://br.linkedin.com/in/rodrigovicenzo)',
    ] },
  { type: 'p', text: 'decided to accept the following challenge:' },
  { type: 'p', text: '“Strengthen Brazilians’ mental health using UX Design”' },
  { type: 'h2', text: 'Understanding the problem' },
  { type: 'p', text: '[According to WHO, Brazil is the most anxious country in the world](https://www.em.com.br/app/noticia/saude-e-bem-viver/2022/07/03/interna_bem_viver,1376936/brasil-o-pais-mais-ansioso-do-mundo.shtml) and, to make matters worse, [there was an 80% increase in cases during the pandemic alone and another 50% increase in cases of depression](https://veja.abril.com.br/saude/casos-de-depressao-e-de-ansiedade-dobram-durante-quarentena/). This means a total of **20 million Brazilians with anxiety disorder** and more than **12 million with depression.** Furthermore, on average, [**24% of the cases of anxiety will evolve into depression**](https://www.estarsaudemental.com.br/depressao-ansiosa/#:~:text=Estima-se%20que%20em%2024,evoluir%20para%20um%20quadro%20ansioso%E2%80%9D.&text=Preste%20aten%C3%A7%C3%A3o%20nestes%20dados:%20estima,Transtorno%20Depressivo%20Maior%20%28TDM%29), which makes the situation even worse.' },
  { type: 'p', text: 'The scenario is worrisome, with no sign of getting better. In this chaos, the psychologists present themselves as the main agents for treating these cases, however, **there are still barriers that prevent the situation from improving.**' },
  { type: 'h2', text: 'Project objective' },
  { type: 'p', text: '“Our objective is to **understand the barriers that make it difficult for Brazilians to take care of their own mental health and perform the necessary treatments** and, thus, to create a solution to overcome them.”' },
  { type: 'p', text: 'Before scaling, the focus will be to ensure the best solution for the user’s problem with the least effort. Therefore, we will work with a reduced number of users, using two main goals (based on the H.E.A.R.T. framework):' },
  { type: 'ul', items: [
      'Satisfaction: achieve NPS greater than 75 (excellence zone) in the first 6 months;',
      'Retention: have at least 60% of active users (users who have recurring sessions) in the first 6 months.',
    ] },
  { type: 'p', text: 'After the initial stage of validation, we will direct our goals towards scaling the solution, in other words, we will mainly focus on increasing user numbers.' },
  { type: 'h2', text: 'Creating empathy' },
  { type: 'p', text: 'In order to have a deeper understanding of who these people are and what they are like, we built three proto-personas, based on our desk research. They functioned as a guide for us to conduct our research and were structured as a CSD matrix for each proto-persona, which helped us validate our suppositions and understand what the users’ pains really were. Our initial main suppositions and doubts were:' },
  { type: 'img', src: '/cases/sophia-mental-health/02.png', alt: 'Main suppositions and doubts of our CSD matrix', w: 2000, h: 1072, caption: 'Main suppositions and doubts of our CSD matrix' },
  { type: 'h3', text: 'Quantitative research' },
  { type: 'p', text: 'We created two forms, one for patients and one for psychologists, basing the questions on the most relevant hypotheses and doubts of our CSD matrix. The questionnaire, focused on patients with almost 250 responses, helped us understand more about the users.' },
  { type: 'p', text: 'Check out the [interactive dashboard made in Google Data Studio](https://datastudio.google.com/reporting/21a883f1-cc10-4731-a5ea-862f6cdb2c0f).' },
  { type: 'p', text: '**Patients**' },
  { type: 'img', src: '/cases/sophia-mental-health/03.png', alt: 'Of men: 61% seek professional help when they need it; 77% talk about their problems and feelings, even if only when they’re not well; only 4% who stated they don’t need a psychologist, said that they already considered or tried to take their own lives.', w: 2000, h: 676, caption: 'Data that invalidate some of our initial hypotheses' },
  { type: 'p', text: 'Contemporary men care more about their mental health than we thought. Despite that, among men who said they don’t go to a psychologist because they don’t need one (the stereotype in our proto-personas), only 4% said they had already considered or tried to take their own lives. This value is very contrasting with the totality of the research, in which more than 55% said that they had already thought about suicide. Our conclusion is that **they don’t want, and believe they don’t need, the help of these professionals** and, consequently, ours.' },
  { type: 'img', src: '/cases/sophia-mental-health/04.png', alt: '55% of the respondents already considered taking their own lives.', w: 2000, h: 816, caption: 'Relevant data from all participants' },
  { type: 'p', text: 'On the other hand, the research didn’t just help us in **making sure that some of our suppositions were valid**, but it also **brought us new insights** on how we could solve the challenge:' },
  { type: 'img', src: '/cases/sophia-mental-health/05.png', alt: '20% see a psychologist regularly. 58% don’t take care of their mental health in any way. 30% stopped going or never went to a psychologist for financial reasons. 13% of women and 10% of all participants don’t feel comfortable going to a psychologist.', w: 2000, h: 606, caption: 'Data that brought us new opportunities to explore' },
  { type: 'p', text: 'These data, especially the last two, brought many questions for us to investigate on a deeper level, as we know that…' },
  { type: 'p', text: '“… there is a discrepancy between what people say and what they really think, feel and how they act.”' },
  { type: 'p', text: '**Psychologists**' },
  { type: 'p', text: 'The quantitative research with the psychologists, despite not being as revealing as the qualitative part, gave us some directions of what we could explore:' },
  { type: 'img', src: '/cases/sophia-mental-health/06.png', alt: '96% already attend online because of the pandemic. 40% pointed lack of privacy as a problem.', w: 2000, h: 612, caption: 'Important data about the research with psychologists' },
  { type: 'ul', items: [
      '_Is “online” still a problem?_',
      '_Why and how do these problems with virtual spaces happen?_',
      '_How do these professionals acquire new clients?_',
    ] },
  { type: 'h3', text: 'Qualitative research' },
  { type: 'p', text: 'We did **interviews to dig into the whys and into the feelings of our users**, all of them related to points that were found in the quantitative research.' },
  { type: 'p', text: 'In order to write the **interview scripts**, we linked each one of the points that we would like to understand better to an open question with observations of what should be deepened, how and why.' },
  { type: 'img', src: '/cases/sophia-mental-health/07.png', alt: 'Excerpt taken from the patient’s interview script', w: 692, h: 479, caption: 'Excerpt taken from the patient’s interview script' },
  { type: 'p', text: 'Check out the [complete interview script](https://docs.google.com/document/d/1PqHnOEeD0RZYaiGSYMs77eUcSsUeFr7MmYmCZOy-aCY/edit?usp=sharing).' },
  { type: 'p', text: 'After conducting more than 20 interviews, we could observe patterns that clarified key points for the project continuation:' },
  { type: 'p', text: '**Patients**' },
  { type: 'ol', items: [
      '**The “financial problem” was not that much “financial”.** There are several popular initiatives and cheap alternatives for those who can’t pay. What happens is that in the majority of the cases **people can’t find a psychologist that they like, feel comfortable and really trust** in these places. _Those “10%” in the quantitative research turned out to be much more significant than they seemed._',
      '**People want fast results.** When they finally find a good professional, **most of them stop the treatment after feeling a little bit better.** Consequently, symptoms come back, generating a vicious cycle.',
      '**Online therapy is an alternative.** Most people who have started doing online therapy felt more comfortable because they’re in a personal space behind their screens, so **they feel safer to talk about their problems.**',
    ] },
  { type: 'p', text: '**Psychologists**' },
  { type: 'ol', items: [
      '**They still strongly prefer in-person therapy rather than online.** Actually, psychologists have a lot of ease with virtual spaces and they see many advantages in it, but they still think **it’s important to have a physical place to attend in-person.**',
      '**Attracting clients for therapy is a problem.** Psychologists acquire clients by word of mouth marketing and by providing therapy through health insurance. The first one is a slow process and the second one doesn’t give a good profit.',
    ] },
  { type: 'h3', text: 'Personas and User Journeys Map' },
  { type: 'p', text: 'In order to align our new discoveries with the team, we redrew the 3 personas and their respective journeys:' },
  { type: 'img', src: '/cases/sophia-mental-health/08.png', alt: 'Persona 1', w: 960, h: 540, caption: 'Persona 1' },
  { type: 'img', src: '/cases/sophia-mental-health/09.png', alt: 'User journey map for the persona 1', w: 960, h: 540, caption: 'User journey map for the persona 1' },
  { type: 'p', text: 'Check out the [3 complete personas and the user journeys map](https://docs.google.com/presentation/d/1JhYKJ4DjQBzZbRSdxegeLJnJQzrMQmmBaH0QdSv7iyk/edit?usp=sharing).' },
  { type: 'h2', text: 'Ideation' },
  { type: 'p', text: 'With the validated personas and user journeys in our hands, we used the “How Might We?” framework to **link our learnings with the idea generation.** We rewrote each one of the main points in virtual post-its using the HMW and **we prioritized them in an impact vs effort matrix** using Miro.' },
  { type: 'img', src: '/cases/sophia-mental-health/10.jpg', alt: 'Impact vs effort matrix', w: 2000, h: 1670, caption: 'Impact vs effort matrix' },
  { type: 'p', text: 'We identified through the matrix what was most relevant for the user and for the business and what would have the least effort.' },
  { type: 'p', text: 'We selected the main HMW and used it to generate solution ideas, taking **only one main focus** and important points to complement it, followed by secondary ones, which were, of course, still **relevant for the whole experience.**' },
  { type: 'img', src: '/cases/sophia-mental-health/11.jpg', alt: 'Prioritized “how might we”', w: 2000, h: 1722, caption: 'Prioritized “how might we”' },
  { type: 'p', text: 'For each one of these points, we generated several ideas of solution — firstly individually and secondly as a group — , using 4 constraints: _solutions that we could build with 1 billion dollars, without money, using magic and with futuristic technologies._ Although some ideas generated with this framework seem impossible to implement, **it’s very easy to make them tangible during the process and it’s where most of the innovative ideas come from.**' },
  { type: 'p', text: 'Of all these ideas, we voted on the best ones and discussed each one of them, taking into account factors such as **technical viability, available resources, relevance for the business and how these ideas could interact with each other.** Then we started to **deepen the solution.**' },
  { type: 'img', src: '/cases/sophia-mental-health/12.jpg', alt: 'Solution value proposition', w: 2000, h: 666, caption: 'Solution value proposition' },
  { type: 'img', src: '/cases/sophia-mental-health/13.jpg', alt: 'Defining the solution', w: 2000, h: 1746, caption: 'Defining the solution' },
  { type: 'p', text: 'Check out the [complete ideation process on Miro](https://miro.com/app/board/uXjVPdM9iY0=/?share_link_id=83332698073).' },
  { type: 'h2', text: 'Benchmarking' },
  { type: 'p', text: 'We chose to just analyze our competitors after getting a better understanding of what the solution would be to not let the analysis induce it, keeping the innovation, but also trying to grow our unfair advantage. So we mapped 5 competitors — [Vittude](https://www.vittude.com/), [Zenklub](https://zenklub.com.br/), [CVV](https://www.cvv.org.br/), [7 cups](https://www.7cups.com/) and [Fepo](https://www.fepo.com.br/) — , analyzed each one of them and created a comparative table between them.' },
  { type: 'img', src: '/cases/sophia-mental-health/14.png', alt: 'Comparative table between competitors', w: 1830, h: 1360, caption: 'Comparative table between competitors' },
  { type: 'p', text: 'After the analysis, we reached the following conclusions:' },
  { type: 'ul', items: [
      'Emergency care and volunteer listener program can be an unfair advantage as they don’t exist in Brazilian psychology platforms (7cups is foreign and CVV is not a complete platform, just a phone number to call in emergency situations);',
      'There is still space to develop an initial screening that understands the patient better according to their report, not as a self-diagnosis (which is done in most of them) — our solution starts to do it with the screening by feelings and the artificial intelligence of a match, whose algorithm learns as it does more matches;',
      'We can work with B2B plans to reach this market;',
      'We take advantage of the 7cups idea to create personal growth paths focused on complementing the psychological treatment with individual steps.',
    ] },
  { type: 'h2', text: 'Solution prototype' },
  { type: 'img', src: '/cases/sophia-mental-health/15.jpg', alt: 'One of the sketches of the platform using the Crazy Eights framework', w: 1400, h: 787, caption: 'One of the sketches of the platform using the Crazy Eights framework' },
  { type: 'p', text: 'Before we began to do sketches on paper as in the above picture, we had discussed what technology we would use for the solution, given that “to strengthen Brazilians’ mental health” we mean all of them — therefore, **we need to be inclusive.** Mobile applications have, in our opinion, a more immersive experience, however, **they require a large amount of free memory that simple and old smartphones don’t have.**' },
  { type: 'p', text: 'So we decided on the best of both worlds: **PWA (Progressive Web App)**, which gives both the **immersive experience and no need to download it** and it’s **accessible from a computer** too. It will also help us with the development, **needing less effort**, because we would need fewer developers for the different platforms and also simpler code based on HTML, CSS and Javascript with access to native functions.' },
  { type: 'h3', text: 'Crazy Eights' },
  { type: 'p', text: 'With that said, using the mobile first concept, we designed the app screens using Crazy Eights. It was a moment when a lot of ideas on how to design the same solutions in different ways were brought, always having in mind the personas and the user journeys.' },
  { type: 'img', src: '/cases/sophia-mental-health/16.jpg', alt: 'Hand-drawn paper sketches of six app screens: splash with the logo, choosing patient or professional, an intro to the app, a questionnaire, a list of matched professionals and a professional’s profile with video', w: 624, h: 881 },
  { type: 'img', src: '/cases/sophia-mental-health/17.jpg', alt: 'Eight paper sketches of app screens from the Crazy Eights exercise: post-match home, tutorial, choosing a path, and the steps of the match questionnaire', w: 1279, h: 892 },
  { type: 'img', src: '/cases/sophia-mental-health/18.jpg', alt: 'Eight more paper sketches: home with the match button, the match in progress, the matched professional’s profile, the SOS screen, content, achievements, therapy with chat, and the psychologist’s agenda', w: 1257, h: 896 },
  { type: 'img', src: '/cases/sophia-mental-health/19.jpg', alt: 'Different sketches for the app screens using Crazy Eights', w: 847, h: 600, caption: 'Different sketches for the app screens using Crazy Eights' },
  { type: 'h3', text: 'Screen map' },
  { type: 'p', text: 'To structure our ideas before we dive into the wireframes, we built the app screen map.' },
  { type: 'img', src: '/cases/sophia-mental-health/20.png', alt: 'Screen map', w: 2000, h: 958, caption: 'Screen map' },
  { type: 'h3', text: 'Wireframes' },
  { type: 'p', text: 'We revisited the personas and the journey, our sketches and the screen map to highlight the important points and tie up everything into an experience that creates value for the user, solving their problem with a good usability.' },
  { type: 'p', text: 'In other words, we designed the wireframes using Figma, defining the information architecture and the positioning of the elements in a low-fidelity prototype:' },
  { type: 'img', src: '/cases/sophia-mental-health/21.jpg', alt: 'App screens in a low-fidelity prototype', w: 1400, h: 356, caption: 'App screens in a low-fidelity prototype' },
  { type: 'p', text: 'Browse in the [complete wireframes](https://www.figma.com/proto/StBNiTWGf0ysP4whg9TLZ9/Grupo_UX_Unic%C3%B3rnio?node-id=402%3A2&scaling=scale-down).' },
  { type: 'h2', text: 'Usability tests' },
  { type: 'p', text: 'The low-fidelity prototype was tested with 5 users on the following tasks:' },
  { type: 'ul', items: [
      '_Search for a psychologist_',
      '_Begin a session of virtual therapy_',
      '_Start an emergency attendance_',
    ] },
  { type: 'h3', text: 'Tests report' },
  { type: 'p', text: '_Alert: high-fidelity prototype spoilers!_' },
  { type: 'p', text: '**1. Make the match before signing up.** The reason is to have one less barrier in order for the user to perceive the value that the platform delivers and decrease the bounce rate. With that, the next step after the onboarding becomes the match, not the signing up.' },
  { type: 'img', src: '/cases/sophia-mental-health/22.png', alt: 'Comparison of the last onboarding screen before and after the tests', w: 1080, h: 1144, caption: 'Comparison of the last onboarding screen before and after the tests' },
  { type: 'p', text: '**2. Match button not found.** 100% of the users didn’t identify the magnifying glass icon and its card as an action button, so we had to redesign it.' },
  { type: 'img', src: '/cases/sophia-mental-health/23.png', alt: 'Comparison of the match screen before and after the tests', w: 1080, h: 1144, caption: 'Comparison of the match screen before and after the tests' },
  { type: 'p', text: '**3. Difficulties in answering the questionnaire.** It happened mainly because feelings, emotions and physical symptoms generally have different intensities, therefore we put them in a numerical scale.' },
  { type: 'img', src: '/cases/sophia-mental-health/24.png', alt: 'Comparison of one of the questionnaire screens before and after the tests', w: 1080, h: 1144, caption: 'Comparison of one of the questionnaire screens before and after the tests' },
  { type: 'p', text: '**4. Virtual attendance not found.** Users struggled to find the access to their virtual counseling, so we created an access button in the card of scheduled therapy and also a menu of attendances.' },
  { type: 'img', src: '/cases/sophia-mental-health/25.png', alt: 'Comparison of the home screen before and after the tests', w: 1080, h: 1144, caption: 'Comparison of the home screen before and after the tests' },
  { type: 'h3', text: 'Writing test' },
  { type: 'p', text: 'In the usability tests, we also noted that users skipped the whole onboarding screens without reading it. Therefore, **using the tool** [**_VisualEyes_**](https://www.visualeyes.design/)**, we analyzed the readability and user attention** in these screens. As a result, we **rewrote and shortened the texts** and **added a skip button**, creating an easier to read and to understand experience and also less tiring for hurried users.' },
  { type: 'img', src: '/cases/sophia-mental-health/26.png', alt: 'Comparison of one of the onboarding screens before and after the tests', w: 2000, h: 1482, caption: 'Comparison of one of the onboarding screens before and after the tests' },
  { type: 'h2', text: 'Branding' },
  { type: 'h3', text: 'Naming' },
  { type: 'p', text: 'The naming process was based on two aspects:' },
  { type: 'ol', items: [
      '**Mental health** (segment)',
      '**Affinity** between the psychologist and the patient (value proposition)',
    ] },
  { type: 'p', text: 'From them, an unfolding was made in a brainstorm, when more creative options arose.' },
  { type: 'img', src: '/cases/sophia-mental-health/27.jpg', alt: 'Naming process from the main aspects', w: 1400, h: 1050, caption: 'Naming process from the main aspects' },
  { type: 'p', text: '**Sophia.**' },
  { type: 'p', text: 'From Greek **sophía**, it means wisdom and conveys the idea of self knowledge.' },
  { type: 'p', text: 'We believe that “Sophia” conveys more empathy, openness and humanity to the user by having a personified name.' },
  { type: 'p', text: '“Sophia will guide you in the search of the best professional to surpass your conflicts and crises, helping to strengthen your mental health and provide self knowledge, besides being always present ‘for the better and for the worse.’”' },
  { type: 'h3', text: 'Logo' },
  { type: 'img', src: '/cases/sophia-mental-health/28.jpg', alt: 'Logo concept: a pair of rings (alliance, connection, partnership) plus an embrace (empathy, affinity) equals the Sophia ‘S’, two arcs ending in dots like two people holding each other', w: 1646, h: 624 },
  { type: 'img', src: '/cases/sophia-mental-health/29.jpg', alt: 'Logo creation thinking', w: 1215, h: 1235, caption: 'Logo creation thinking' },
  { type: 'p', text: '**Colors**' },
  { type: 'p', text: '**Orange** mixes active and invigorating emotions, which seek to arouse feelings of vitality and happiness.' },
  { type: 'p', text: '_Associations: energy, enthusiasm, prosperity, cordiality, change._' },
  { type: 'p', text: '**Purple** conveys tranquility and helps creativity, showing sophistication.' },
  { type: 'p', text: '_Associations: spirituality, authenticity, veracity, quality, introspection._' },
  { type: 'h2', text: 'Styleguide' },
  { type: 'p', text: '**Colors:** with them practically defined, we chose some variations of the brand colors so we could apply them in the prototype and also some complementary others.' },
  { type: 'img', src: '/cases/sophia-mental-health/30.png', alt: 'Colors in the styleguide', w: 780, h: 407, caption: 'Colors in the styleguide' },
  { type: 'p', text: '**Typography:** we opted for two different fonts for titles and text, both sans serif, bringing with them a sensation of modernity — the main reason we chose DIN Next Rounded LT Pro, which strengthens the message with rounded shapes. As a complement, Source Sans Pro, for the text, has excellent legibility, besides being a widely used font on the web, which speeds up page loading.' },
  { type: 'img', src: '/cases/sophia-mental-health/31.png', alt: 'Typography in the styleguide', w: 1324, h: 906, caption: 'Typography in the styleguide' },
  { type: 'p', text: '**Buttons and forms:** we chose slightly rounded shapes, but not so much, as in halfway between lightness and seriousness.' },
  { type: 'img', src: '/cases/sophia-mental-health/32.png', alt: 'Buttons and forms in the styleguide', w: 1400, h: 445, caption: 'Buttons and forms in the styleguide' },
  { type: 'h2', text: 'High-fidelity prototype' },
  { type: 'p', text: 'Finally, we built the high-fidelity prototype using Adobe XD, based on the wireframes, usability tests and styleguides.' },
  { type: 'p', text: 'Check out the [full navigable prototype](https://xd.adobe.com/view/ce110830-589e-4dc4-b04e-c3637b9199ce-9b42/screen/4e9a3691-3271-4e5a-8fd8-f47c2277b99b/).' },
  { type: 'img', src: '/cases/sophia-mental-health/33.jpg', alt: 'App screens in a high-fidelity prototype', w: 1400, h: 931, caption: 'App screens in a high-fidelity prototype' },
  { type: 'h2', text: 'Next steps' },
  { type: 'p', text: 'As a consequence of the prioritization, we raised some important points to be developed after the launching of the MVP (Minimum Viable Product). They are:' },
  { type: 'ul', items: [
      'AI (Artificial Intelligence) that talks and counsels patients',
      'In-person clinics in big metropolises for psychologists to use and offer in-person counseling (eliminating the need and most of the costs with a physical space for them)',
    ] },
  { type: 'p', text: 'Besides that, the project still has space for improvement, as we know that the development of a product never ends.' },
  { type: 'p', text: '“Users change over time, and so must the product.”' },
  { type: 'h2', text: 'Final considerations' },
  { type: 'p', text: 'We are grateful to **our mentors** [**Leandro Rezende**](https://www.linkedin.com/in/lbrezende/?locale=en_US) **and** [**Rafael Frota**](https://www.linkedin.com/in/imrafaelfrota/?locale=en_US)**, of** [**UX Unicórnio**](https://www.linkedin.com/school/uxunicornio/), for all the learnings that we had through the process.' },
  { type: 'h2', text: 'Team members contact' },
  { type: 'ul', items: [
      '[LinkedIn João Vitor Fatoretto](https://www.linkedin.com/in/joaovitorfatoretto/?locale=en_US)',
      '[LinkedIn Rodrigo Vicenzo](https://br.linkedin.com/in/rodrigovicenzo)',
      '[LinkedIn Paulo Ortega](https://www.linkedin.com/in/phortega/)',
    ] },
];
